# this is optional, use `pre-commit autoupdate` to get the latest rev!
repos:
- repo: local
  hooks:
    - id: pyupgrade
      name: pyupgrade
      language: system
      types: [python] # This ensures only Python files are passed
      entry: pyupgrade
      args: [--py39-plus]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      # use your preferred Python version
      language_version: python3.9
      additional_dependencies: ["mypy==1.8.0"]
      # trigger for commits changing Python files
      types: [python]
      # use require_serial so that script
      # is only called once per commit
      require_serial: true
      # print the number of files as a sanity-check
      verbose: true
