[tool.ruff]
# Specify the paths you want Ruff to ignore
exclude = ["build/", "dist/"]

# Specify individual checks to enable
# (useful if you have used --select or --extend-select)
extend-select = ["E1", "W2"]

# Specify individual checks to disable
# (useful if you have used --ignore or --extend-ignore)
extend-ignore = ["E203"]

# Set the max line length (default is 88)
max-line-length = 120
