name: Publish Docker image

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Free Disk Space
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup tag
      - name: Setup tag
        id: setup_tag
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            echo "::set-output name=tag::francescooteri/af2_msa_serverless:dev"
          else
            echo "::set-output name=tag::francescooteri/af2_msa_serverless:latest"
          fi

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.setup_tag.outputs.tag }}
